### ISSUE TITLE
Add an option to delete the message

### ISSUE THREAD

**Issue by adyanth** [webex/webex-node-bot-framework#17]
As of now, I do not see an option to delete a message.

**Comment by jpjpjp** [comment]
@adyanth, the framework does not provide a "shortcut" for deleting a message but the [full set of interfaces in the Webex SDK](https://webex.github.io/webex-js-sdk/api/) are always available to you.   Here is an example of an app that implemented a "delete" command that when sent as a threaded reply to a message previously posted by a bot, would cause the bot to delete the message.

```javascript
framework.hears('delete', function (bot, trigger) {
    let msg = 'I can only process a "delete" command as a threaded reply to a message that I posted';
    if (trigger.message.parentId) {
      bot.webex.messages.remove(trigger.message.parentId)
        .catch(e => {
          logger.info(`Failed to delete a parent message. ` +
            `This is usually because it wasn't posted by the bot.  Error: ${e.message}`);
          bot.reply(trigger.message, msg);
        });
    } else {
      bot.reply(trigger.message, msg);
    }
  });
```
By the way, feel free to join the conversation in the [Framework Discussion Space](https://eurl.io/#BJ7gmlSeU)

**Comment by adyanth** [comment]
Okay, that works. I was making a API call to the delete endpoint like a fool 😄
