### ISSUE TITLE
Bot replies "markdown" after being up for several hours

### ISSUE THREAD

**Issue by armando-sentinel** [webex/webex-node-bot-framework#18]
I have been struggling trying to find what's the issue with this but after the server is up for several hours the bot stops replying with an accurate response and instead keeps replying "markdown". Restart fixes the problem.

**Comment by jpjpjp** [comment]
@armando-sentinel, can you provide an example of a `framework.hears()` handler that is behaving this way?   (BTW, it might be faster to quickly resolve your problem if you join the discussion in the [Framework Discussion Space](https://eurl.io/#BJ7gmlSeU)

**Comment by jpjpjp** [comment]
Hi @armando-sentinel, haven't heard back from you on this so I'm going to close this issue.   Feel free to reopen with more details if you have them.
